name: Check PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  Chek-PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Prepare env
        run: unzip -P ${{ secrets.TBD_SESSION_TESTS }} tdlight-session.zip
      - name: Execute Gradle build
        env:
          TBD_TELEGRAM_TEST_API_ID: ${{ secrets.TBD_TELEGRAM_TEST_API_ID }}
          TBD_TELEGRAM_TEST_BOT_TOKEN: ${{ secrets.TBD_TELEGRAM_TEST_BOT_TOKEN }}
          TBD_TELEGRAM_TEST_HASH: ${{ secrets.TBD_TELEGRAM_TEST_HASH }}
        run: ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Run run Sonarqube
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
